### ISSUE TITLE
More detail on admin_notice

### ISSUE THREAD

**Issue by SnoOpyMinhThang** [Seravo/wp-custom-bulk-actions#3]
I use this plugin to create bulk action "Permanent Delete".
It works fine, but text-only admin_notice not has enough information for notice: "Permanent deleted posts".
I need some variables pass to admin_notice to help build detail notice like: "Permanent deleted posts with IDs: 500, 501" or "Permanent deleted posts with names: Hello world, MinhThang's Blog".

Thanks :)

[MinhThang's Blog](http://minhthang.name.vn)

**Comment by onnimonni** [comment]
Sounds good, If You a make pull request I will be Happy to merge it :)

**Comment by cyberwani** [comment]
Hi @onnimonni  and @SnoOpyMinhThang 
I send a pull-request to display single ID and Multiple IDs notices.

https://github.com/Seravo/wp-custom-bulk-actions/pull/4
